#!/bin/bash
# Model configuration switcher
# Supports presets and custom model combinations

GENERAL_MODEL=""
CODING_MODEL=""

# Parse arguments
if [ "$#" -eq 1 ]; then
  # Preset mode
  case "$1" in
    "granite")
      GENERAL_MODEL="ollama:granite3.3:8b"
      CODING_MODEL="ollama:qwen2.5-coder:14b"
      ;;
    "optimized")
      GENERAL_MODEL="ollama:mistral"
      CODING_MODEL="ollama:qwen2.5-coder:14b"
      ;;
    "generic")
      GENERAL_MODEL="ollama:mistral"
      CODING_MODEL="ollama:mistral"
      ;;
    *)
      echo "❌ Unknown preset: $1"
      echo ""
      echo "Usage:"
      echo "  ./switch_env.sh <preset>"
      echo "  ./switch_env.sh <general_model> <coding_model>"
      echo ""
      echo "Presets:"
      echo "  granite    - Granite 3.3 for general + Qwen for coding"
      echo "  optimized  - Mistral for general + Qwen for coding"
      echo "  generic  - Mistral for everything"
      echo ""
      echo "Custom example:"
      echo "  ./switch_env.sh granite3.3:8b qwen2.5-coder:14b"
      exit 1
      ;;
  esac
elif [ "$#" -eq 2 ]; then
  # Custom model mode
  GENERAL_MODEL="ollama:$1"
  CODING_MODEL="ollama:$2"
else
  echo "Usage:"
  echo "  ./switch_env.sh <preset>"
  echo "  ./switch_env.sh <general_model> <coding_model>"
  echo ""
  echo "Presets:"
  echo "  granite    - Granite 3.3 (general) + Qwen (coding)"
  echo "  optimized  - Mistral (general) + Qwen (coding)"
  echo "  generic    - Mistral for everything"
  echo ""
  echo "Custom examples:"
  echo "  ./switch_env.sh granite3.3:8b qwen2.5-coder:14b"
  echo "  ./switch_env.sh mistral llama3:8b"
  echo ""
  echo "Current config:"
  grep '^COORDINATOR_MODEL=' .env | cut -d= -f2
  grep '^CODEBASE_MODEL=' .env | cut -d= -f2
  exit 0
fi

# Generate .env from template
echo "Generating .env with:"
echo "  General model: $GENERAL_MODEL"
echo "  Coding model:  $CODING_MODEL"

cat > .env << EOF
# Auto-generated by switch_env.sh
# General model: $GENERAL_MODEL
# Coding model: $CODING_MODEL

# === GENERAL SETTINGS ===
OLLAMA_BASE_URL=http://localhost:11434/v1
DEBUG=false
LOG_LEVEL=INFO

# === DEFAULT MODEL ===
DEFAULT_MODEL=$GENERAL_MODEL
DEFAULT_TEMPERATURE=0.3
DEFAULT_RETRIES=2

# === AGENT-SPECIFIC MODELS ===

# Coordinator - tool routing and delegation
COORDINATOR_MODEL=$GENERAL_MODEL
COORDINATOR_TEMPERATURE=0.2

# Codebase Investigator - code analysis
CODEBASE_MODEL=$CODING_MODEL
CODEBASE_TEMPERATURE=0.3

# File Editor - file operations (CRITICAL for tool calling)
FILE_EDITOR_MODEL=$GENERAL_MODEL
FILE_EDITOR_TEMPERATURE=0.1

# Testing Agent - test generation
TESTING_MODEL=$GENERAL_MODEL
TESTING_TEMPERATURE=0.2

# Documentation Agent - docs generation
DOCUMENTATION_MODEL=$GENERAL_MODEL
DOCUMENTATION_TEMPERATURE=0.5

# Refactoring Agent - complex refactoring
REFACTORING_MODEL=$CODING_MODEL
REFACTORING_TEMPERATURE=0.2
EOF

echo "✅ Configuration updated!"
echo ""
echo "Active models:"
echo "  Coordinator:      $GENERAL_MODEL"
echo "  File Editor:      $GENERAL_MODEL"  
echo "  Testing:          $GENERAL_MODEL"
echo "  Documentation:    $GENERAL_MODEL"
echo "  Codebase:         $CODING_MODEL"
echo "  Refactoring:      $CODING_MODEL"
